### ISSUE TITLE
Check xfce4-appmenu-plugin for global menus

### ISSUE THREAD

**Issue by probonopd** [helloSystem/hello#11]
```
sudo apt-get update
sudo apt-get -y install xfce4-appmenu-plugin
```

Add "AppMenu Plugin" to the panel.

> This is an Application Menu (Global Menu) plugin. It is built using __the Unity protocol and libraries__ and provides all features found in the Unity implementation. 

Also check out __the Unity protocol and libraries__ and see if we can use this in a pure Qt desktop.

**Comment by probonopd** [comment]
It does work e.g., with AppImages of Qt-based applications:

![](https://user-images.githubusercontent.com/2480569/82732686-50d53e00-9cfe-11ea-90f0-0681838e15a7.png)

**Comment by probonopd** [comment]
It also works for GoLang (Java based):

![image](https://user-images.githubusercontent.com/2480569/82732736-a9a4d680-9cfe-11ea-86e8-f1615e3f8075.png)

**Comment by probonopd** [comment]
However, I could not get it to work for Firefox yet:

![image](https://user-images.githubusercontent.com/2480569/82732762-c6410e80-9cfe-11ea-8c6a-ba5607ea73a6.png)

**Comment by probonopd** [comment]
It even works for the Scribus Nightly AppImage which bundles practically _everything_:

![image](https://user-images.githubusercontent.com/2480569/82732824-40719300-9cff-11ea-955a-d106c2eb033d.png)

So this seems to be a really robust, interesting solution

**Comment by probonopd** [comment]
But then, it __does not work__ for Inkscape, a Gtk based application. Why?

![](https://user-images.githubusercontent.com/2480569/82732846-69922380-9cff-11ea-8267-a6f25a687973.png)

Didn't Inkscape have global menus in Ubuntu Unity?

**Comment by probonopd** [comment]
I don't quite understand Ubuntu's terminology, what does "indicator" mean? Is a way to say/get "global menu bar at the top of the screen"?

**Comment by probonopd** [comment]
It works for the Xfce desktop itself:

![image](https://user-images.githubusercontent.com/2480569/82732992-474cd580-9d00-11ea-9748-625803b474e6.png)

But not for its own Thunar file manager:

![image](https://user-images.githubusercontent.com/2480569/82733004-5f245980-9d00-11ea-8630-b160d0c29c30.png)

___Why?____

**Comment by probonopd** [comment]
It seems that for MATE, one needs a separate plugin:

https://packages.debian.org/buster/mate-applet-appmenu

**Comment by aguslr** [comment]
For this to work with XFCE applications (Thunar, Parole, Ristretto, etc.), it seems Appmenu needs to be enabled [1] [2]:

```
xfconf-query -c xsettings -p /Gtk/ShellShowsMenubar -n -t bool -s true
xfconf-query -c xsettings -p /Gtk/ShellShowsAppmenu -n -t bool -s true
xfconf-query -c xsettings -p /Gtk/Modules -n -t string -s "unity-gtk-module"
```

![thunar](https://user-images.githubusercontent.com/421687/85392689-6cb94300-b53b-11ea-97a0-7b4005e7cd8e.png)

For good measure, it'd be a good idea to do add the following:

- In `~/.gtkrc-2.0`:

```
gtk-modules="unity-gtk-module"
```

- In `~/.config/gtk-3.0/settings.ini`:

```
gtk-modules=unity-gtk-module
gtk-shell-shows-app-menu=true
gtk-shell-shows-menubar=true
```

- And in `~/.xprofile`:

```
if [ -n "$GTK_MODULES" ]; then
    GTK_MODULES="${GTK_MODULES}:unity-gtk-module"
else
    GTK_MODULES="unity-gtk-module"
fi

if [ -z "$UBUNTU_MENUPROXY" ]; then
    UBUNTU_MENUPROXY=1
fi

export GTK_MODULES
export UBUNTU_MENUPROXY
```

This is for Ubuntu-based distros, otherwise just replace `unity-gtk-module` with `appmenu-gtk-module`.

[1]: https://github.com/rilian-la-te/vala-panel-appmenu#desktop-environment-specific-settings
[2]: https://github.com/rilian-la-te/vala-panel-appmenu/blob/master/subprojects/appmenu-gtk-module/README.md#usage-instructions

**Comment by aguslr** [comment]
Even with all these changes, GTK AppImages don't seem to work (e.g. GIMP and Inkscape):

![gimp_appimage](https://user-images.githubusercontent.com/421687/85393043-e2251380-b53b-11ea-9dcc-b71065f2d833.png)

![inkscape_appimage](https://user-images.githubusercontent.com/421687/85393052-e5b89a80-b53b-11ea-869c-8f1ee29de171.png)

Although LibreOffice's AppImage does work:

![libreoffice_appimage](https://user-images.githubusercontent.com/421687/85393112-f9640100-b53b-11ea-9658-8e84be62b74c.png)

**Comment by aguslr** [comment]
For comparison, these are GIMP and Inkscape working when using the distro's packages:

![inkscape](https://user-images.githubusercontent.com/421687/85393372-68d9f080-b53c-11ea-8dc9-0bd873542f73.png)

![gimp](https://user-images.githubusercontent.com/421687/85393454-8f982700-b53c-11ea-9aa6-2962734efaf9.png)

**Comment by aguslr** [comment]
Regarding Firefox, I know for a fact that it used to work with older LTS versions of Ubuntu since they used a patched version. Here you can see it working in Ubuntu 18.04 LTS:

![firefox_old](https://user-images.githubusercontent.com/421687/85394366-008c0e80-b53e-11ea-9624-2d4371e7987f.png)

But alas, it doesn't work in Ubuntu 20.04 LTS:

![firefox](https://user-images.githubusercontent.com/421687/85394751-90ca5380-b53e-11ea-8e60-198756ff240d.png)

For reference, you can find some patched version in Arch's User repository [1] [2], although I haven't tested them.

[1]: https://aur.archlinux.org/packages/firefox-appmenu/
[2]: https://aur.archlinux.org/packages/firefox-appmenu-bin/

**Comment by aguslr** [comment]
Just extracted Arch's *firefox-appmenu-bin* [[1]] in Ubuntu 20.04 LTS and works as expected:

![firefox_appmenu](https://user-images.githubusercontent.com/421687/85523226-3a205080-b5f6-11ea-90b4-9d7d1664250e.png)

Could this be packed as an AppImage or pull and apply the patch before packing?

[1]: https://aur.archlinux.org/packages/firefox-appmenu-bin/

**Comment by aguslr** [comment]
BTW, all this *magic* seems to be achieved by using *Dbusmenu* [[1]]. I gather that the AppImages that don't have a working AppMenu are not packaging the appropriate *dbusmenu* libraries.

[1]: https://packages.ubuntu.com/search?keywords=dbusmenu

**Comment by probonopd** [comment]
@aguslr you rock. Would you like to start working on this with me for real?

**Comment by probonopd** [comment]
Focusing on Qt-based https://github.com/probonopd/panda-statusbar which is basically the KDE Plasma global menu system without Plasma dependencies.

**Comment by FreezyKaif** [comment]
![image](https://user-images.githubusercontent.com/99117191/159917780-2b579c07-bc16-4200-bb85-8b15c6848a04.png)

WHY THE FUCK WOULD IT HAPPEN ? 

PLEASE HELP

**Comment by probonopd** [comment]
@FreezyKaif do you realize that you are asking in a [helloSystem](https://hellosystem.github.io/) bugracker?

While I can't help you debug this issue on what certainly seems not to be helloSystem, here is the summary of my research into how Global Menus work: https://hellosystem.github.io/docs/developer/menu.html

Maybe it is helpful as a starting point for your debugging. Good luck! (Maybe you'd just like to try helloSystem?)
