### ISSUE TITLE
i have been testing this os on a spare hardware and this is what should be fixed.

### ISSUE THREAD

**Issue by K4mey** [helloSystem/hello#119]
Okay so let me say this before i post these issues, i have been using this system for couple of hours now and i can say that it is indeed beautiful and simple, and I'm very excited about future of this operating system and that's why i will criticize some things that caught my eye because that way the operating system can improve with help of user feedback.

- ctrl + a doesn't work, it just types a (other ctrl + commands also don't work)

- falkon gui is half broken so i had to install firefox, which does work well.

- there's no internet tab in System, so the new installed app such as firefox couldn't be found i also checked all other categories and it's nowhere to be found so i had to run it through terminal or a custom made .sh file on desktop.

- in search tab you can only type 4 letters maximum if it goes over that it will just clear itself.

- there should be a display manager after system is installed, because some more advanced users might want to have multiple desktop environments.

- apps when in full screen go behind the top menu bar which then hides close, minimize functions so then only thing to do is to use dock to close the app and re-open.

- terminal app needs to have the option for multiple tabs so that we can run one program inside it while doing something else in other tab.

- pulling the windows with mouse when it's in full screen doesn't cause it to minimize which it should.

- mounting drives with multiple partitions is broken.

**Comment by probonopd** [comment]
hello @K4mey 

Thanks for testing and for your comments. In general, please open one ticket for each issue __if__ it is not a documented feature and/or a ticket for it does not exist yet. This makes it easier for us to work on, and eventually close, the issues.

> ctrl + a doesn't work, it just types a (other ctrl + commands also don't work)

On Apple keyboards, we use the Command key, and on PC keyboard, we use the Alt key which is in the same location in which the Command key would be on Apple keyboards.

The text "Ctrl" in the menu is wrong and needs to be changed. This is a known issue.
https://github.com/helloSystem/hello/issues/46

> falkon gui is half broken

 I use it every day and apart from some icons missing in the second and subsequent windows, I did not see anything major. Please open a new ticket with details if you see this again.

> firefox, which does work well

Please open a new ticket for this, we have at least one user @grahamperrin who is a Firefox power user.

> there's no internet tab in System, so the new installed app such as firefox couldn't be found

Applications installed via `pkg` are currently not added to the menu automatically yet. We have code that could do it (by creating a wrapper `.app` bundle), but we need to think about application removal as well. Our goal is to provide applications as real `.app` bundles.

In the meantime, you can run `desktop2app /usr/local/share/applications/firefox.desktop /Applications` to create a wrapper `.app` that launches the Firefox installed by `pkg`.

> in search tab you can only type 4 letters maximum if it goes over that it will just clear itself

It clears itself as soon as it finds nothing that matches what you typed.

> terminal app needs to have the option for multiple tabs

I have opened a new issue or this:
https://github.com/helloSystem/ISO/issues/144

> there should be a display manager after system is installed, because some more advanced users might want to have multiple desktop environments.

helloSystem comes with [slim](https://www.freebsd.org/cgi/man.cgi?query=slim) as its display manager (login screen) by default. Configuring more than one desktop environment and disabling automatic login is probably possible, but needs to be done by edting its configuration file. It is not something that most typical helloSystem users would want to do. (I never got it to work properly but that is probably because I didn't fully understand how display managers pick desktop environments - it seems very unintuitive.)

> apps when in full screen go behind the top menu bar which then hides close, minimize functions so then only thing to do is to use dock to close the app and re-open.

Please open a new issue for this with the name of such apps, and a screenshot. E.g., F11 works in Falkon and gives a correct full-screen experience without a menu bar.

> pulling the windows with mouse when it's in full screen doesn't cause it to minimize which it should.

I think you mean "when it's maximized". Unfortunately the window manager we are currently using, Openbox, does not seem to have this feature. If you know how to enable it, please let us know. I would like to see this too.

> mounting drives with multiple partitions is broken.

Please open a new issue for this with details, and please check `/var/log/automount.log`.

Closing here, but please feel free to open individual issues as mentioned above.

**Comment by grahamperrin** [comment]
> * in search tab … clear itself.

Probably https://github.com/helloSystem/Menu/issues/44
