### ISSUE TITLE
dark mode support/thoughts on theming

### ISSUE THREAD

**Issue by briaguya-ai** [helloSystem/hello#145]
what would a dark mode preference implementation look like on helloSystem?

* modern user experience of setting dark/light mode
  * what can users do?
    * set a system/user default
    * override system/user default in individual applications
  * does it work?
    * for supported apps/sites, quite well usually
    * for apps without a dark theme, sometimes things are very broken (white text on a white file picker background broken)
* qt theming
  * works really well for apps that ship with themes
  * feels like the wild west for system/user default stylesheets

possible implementations:
* force system/user stylesheets on apps
  * great for users that like to customize everything
  * can break things quickly
* tie stylesheets to applications
  * make sure apps can see the system/user dark/light mode setting
  * if an application only has one stylesheet, it may look out of place, but it will not look broken
  * possible side effect: [dracula](https://draculatheme.com/) - 128 pages of per app instructions on how to install a theme

tried my best to flesh that out beyond "will there be dark mode?"

**Comment by probonopd** [comment]
Hello @briaguya-ai

helloSystem has no dark mode and dark mode support is currently not on our roadmap. It is not essential to what we are trying to create (a productivity-oriented desktop).

In fact, black text on white background was one key achievement of the early Xerox and Apple GUIs over the usual text-mode screens of the time (green or amber on black background). Let's not fall back to the "dark times".

Reference: Apple Computer, Inc., 1992, Macintosh Human Interface Guidelines, First Printing, November 1992. Addison-Wesley Publishing Company. ISBN 0-201-62216-5 

Likewise, helloSystem has no theming support and theming support is currently not on our roadmap. It is not essential to what we are trying to create (a productivity-oriented desktop). Original versions of the Classic Mac, Mac OS X, and even the iPhone had no theming support whatsoever, which resulted in a very consistent and predictable environment. Likewise, we are aiming for polished out-of-the-box experience that is the same for everyone, so that what an application developer designs will be pixel-perfect what the user sees, no surprises.

(That being said, we are using a qss style sheet that can be edited at runtime. So if you would like to experiment with the design or make changes, all the power to you: https://github.com/helloSystem/QtPlugin/blob/master/stylesheet.qss - but we don't want a system in which normal users can choose from various "random" themes.)
