### ISSUE TITLE
cmd+ctrl+space: emoji

### ISSUE THREAD

**Issue by briaguya-ai** [helloSystem/hello#146]
* input
  *  cmd+crtl+space or :inline_typing: or both?
  * app specific vs system wide?
* display
  * which emoji font? 
    * [noto](https://github.com/googlefonts/noto-emoji)?
    * [twemoji](https://github.com/twitter/twemoji)?
    * [openmoji](https://github.com/hfg-gmuend/openmoji)?
    * something else?
  * helpful for comparison [emojipedia](https://emojipedia.org/raised-fist-dark-skin-tone/)
  * change emoji font as user?

**Comment by probonopd** [comment]
Hello @briaguya-ai

I don't understand what the question is. helloSystem has no keyboard shortcuts for emoji and emoji support is currently not on our roadmap. It is not essential to what we are trying to create (a productivity-oriented desktop).

**Comment by briaguya-ai** [comment]
> emoji support is currently not on our roadmap

@probonopd that answers the question then

i can imagine cases where poor emoji rendering/input support could hinder productivity, but i can see how it's non-essential

**Comment by probonopd** [comment]
We seem to have some emoji support, as the following are displayed on helloSystem (albeit as black-and-white outine artwork):
😃,😎, ❤️,🙊,

**Comment by jobukkit** [comment]
> I don't understand what the question is. helloSystem has no keyboard shortcuts for emoji and emoji support is currently not on our roadmap. It is not essential to what we are trying to create (a productivity-oriented desktop).

Rendering text properly is a baseline expectation of a productivity-oriented desktop.

> We seem to have some emoji support, as the following are displayed on helloSystem OK: 😃,😎, ❤️,🙊,

That's because the GitHub webapp can render emoji's by itself. If you go to a normal website, emoji's aren't rendered. Putting the [Blobmoji](https://github.com/C1710/blobmoji/releases) font in `/usr/local/share/fonts/TTF` allows Falkon to render emoji's properly, though not the rest of the system yet.

**Before:**

![Schermafbeelding 2021-12-14 om 13 57 55](https://user-images.githubusercontent.com/2750434/146002931-6bc48b80-25ff-45c1-ab17-85e945df9ca3.png)

**After:**

![Schermafbeelding 2021-12-14 om 13 58 44](https://user-images.githubusercontent.com/2750434/146002937-495a0a1e-92ed-4b7b-8dd6-2bdaf069ec7c.png)

Please consider including that font by default, that would be a good start.

**Comment by probonopd** [comment]
We should probably include an Emoji font download in a future Fonts utility.

**Comment by jobukkit** [comment]
If emoji's show up as white boxes in your e-mails, you'd sooner think "this OS doesn't support Unicode" than "I should download an emoji font using the Fonts utility". If you really don't want to include a proper emoji font for some reason, you could include [Symbola](https://dn-works.com/ufas/), a monochrome font that covers various Unicode symbols including the most common emoji's.
