### ISSUE TITLE
Large screen support / Scaling

### ISSUE THREAD

**Issue by bmentink** [helloSystem/hello#176]
I have a large wide screen and have not found a way to be able to scale the icons/text to  a larger size.
I have attached a screen shot. Also, the "white" is not white, it is an off-white  .... is there a way to set the default color temperature?
![screen](https://user-images.githubusercontent.com/10123911/123171884-5691db80-d44a-11eb-9438-f2fbd0e93aa6.jpg)

**Comment by linuxkettle** [comment]
I envy your screen resolution.

Anyway, I believe some Hi-DPI features are included already in helloSystem, it appears to just be a matter of finding them. I'll update when I find it.

**Comment by linuxkettle** [comment]
I believe the program that determines screen size is on line 186 of `/usr/local/bin/start-hello`:
```
units -q -t  ${vertical_cm}" cm" inches | cut -d "." -f 1
```
and line 184:
```
cat /var/log/Xorg.0.log | grep "Max Image Size \[cm\]" | rev |  cut -d ":" -f 1 | rev | xargs | tail -n 1
```

The only thing is, *no such line exists*, which leads me to believe that something changed since @probonopd saw that information. Running `grep Max` doesn't come up with anything of use either:
```
[    60.847] (==) Max clients allowed: 256, resource mask: 0x1fffff
```

**Comment by probonopd** [comment]
> I have a large wide screen

What is the physica heigh and width of your screen in inches or cm?
I am asking because looking at your screenshot it looks actually _correct_ (as designed) to me, assuming that the physical height of your screen is around 25 cm in height or more.

In case the physical height of your screen is significantly lower, then you have a HiDPI screen, in which case the software should render everything much larger. But since you write you have a "large" screen, I assume that it is not a HiDPI screen. Do you know the resolution of your screen in pixels per inch (from the datasheet, not from what some software says)?

> have not found a way to be able to scale the icons/text to a larger size.

The UI font text size is currently fixed and cannot be changed.
The icon size can be set in Edit -> Preferences -> Display.
The standard icon size is 36x36 pixels, but can be increased up to 96x96 pixels.

> Also, the "white" is not white, it is an off-white .... is there a way to set the default color temperature?

The color temperature is automatically adjusted throughout the day based on your location and the season to give [circadian lighting](https://www.thelightingpractice.com/what-is-circadian-lighting/). Check that your timezone and date are set correctly if this is way off for you. In case you want to disable this altogether, you need to comment out `redshift` from the `/usr/local/bin/start-hello` start script, log out, and log in again.

**Comment by bmentink** [comment]
@probonopd 
The screen resolution is 3440x1440, the height is 33cm .... it is a big screen. Thanks for the pointer to increase the icon size, that will help. The UI font text size is barely manageable with these tired old eyes, but will cope .. :)

**Comment by linuxkettle** [comment]
I believe if you open /usr/local/share/applications, there is a Look and Feel app, the font settings are there. You can change the font to Comic Sans MS 24pt if you like ;~)

**Comment by bmentink** [comment]
No app to do with look-and-feel in that Folder .. cheers

**Comment by linuxkettle** [comment]
> No app to do with look-and-feel in that Folder

Then I need to find out which desktop environment I've been messing around with. I think it'll be in the `lxqt-config` package:
```
sudo pkg install lxqt-config
lxqt-config
```
Look and Feel should appear there.

**Comment by linuxkettle** [comment]
Yes, I've confirmed that works.

**Comment by bmentink** [comment]
Hmmm, I installed that package, and all I get is these...

```
lxqt-backlight_backend          lxqt-globalkeysd
lxqt-config-globalkeyshortcuts
```

**Comment by linuxkettle** [comment]
`sudo pkg install lxqt-config-appearance`?

**Comment by bmentink** [comment]
Yep that's the one ... tried changing font size .. nothing seems to happen.

**Comment by linuxkettle** [comment]
Hmm...

Same here, nothing changes.

KDE System Settings has an option to change screen scaling, also font resolution. I haven't tried the scaling but fonts works.

**Comment by probonopd** [comment]
@bmentink 

> The screen resolution is 3440x1440, the height is 34cm .... it is a big screen. 

So in this case resolution setting works as designed. You don't have a HiDPI screen.
Looks like what you are after is increasing the size of the UI elements.

> Thanks for the pointer to increase the icon size, that will help. The UI font text size is barely manageable with these tired old eyes, but will cope .. :)

> How do I set the icon size in the bottom panel?

The Dock (or "bottom panel", as you call it) does currently not have this feature implemented.
If you would like to see it, please open a feature request in https://github.com/helloSystem/Dock/issues/ stating that you would like to see icon sizes in the Dock follow icon sizes on the desktop. This could be done by the Dock checking for Filer settings and use those, if they exist, rather than hardcoding one icon size.

> EDIT: After changing the icon size, the folder icons are now larger, but double clicking to open no longer works. I have to single click select the folder, then right click open.
>
> EDIT2: Found if you put the mouse pointer towards bottom of icon, you can double click open. Seems the clickable area has not increased to the same area as the visible icon.

This is a known issue which I think is unrelated to icon sizes. With _some_ icons/in _some_ circumstances there seems to be an issue with the clickable area: 
https://github.com/helloSystem/ISO/issues/133

Do you find that with some icon sizes the issue goes away?

> PS: The screen color tempearture would be wrong because my location is still set to NY, not NZ as it should be. I had to set my language as English(US) as I normally do, but it seems my location gets set based on that rather than my actual location.
(By the way, I ticked the box during installation and it showed Pacific/Auckland ...but it never carried that setting through, rather it defaulted to NY. Hope that makes sense ..

Yes, that thing is apparently not working properly. 
https://github.com/helloSystem/Utilities/issues/37

**Comment by bmentink** [comment]
@probonopd 
Thanks for the confirmation. Regarding the Dock icon sizes, I don't think their size should be tied to the other system icons, but maybe have a separate adjustable setting ... I will place in a feature request.

**Comment by thehotery** [comment]
there's no way to use scaling for hidpi displays? I'm using 4k 27" viewsonic monitor connected with displayport on nvidia 970 and  tried `xrandr --output DP-0 --scaling 2x2`  but result is strange - all image became small "window" (1/4 of whole screen) in left top of screen. Maybe i'm wrong with that command, please correct me, in linux its usually works with just gui tool..

**Comment by probonopd** [comment]
Here is our HiDPI detection:

https://github.com/helloSystem/ISO/blob/experimental/overlays/uzip/hello/files/usr/local/bin/start-hello#L196-L212

Maybe it isn't working properly in your case. Can you find out why?
