### ISSUE TITLE
Is helloSystem internationalized and can I choose another language?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [helloSystem/hello#179]
Does helloSystem not support other languages? I mean, is English the only language you can choose after installation? Is it internationalized?

**Comment by linuxkettle** [comment]
helloSystem supports a growing number of languages, there is information about Crowdin somewhere, where you can improve the translations.

@probonopd uses German, judging by his screenshots.

**Comment by probonopd** [comment]
Thanks for the question @Yakumo-Yukari. This is not fully working yet. Any help is appreciated.

* The Qt (C++) based components _should_ be translatable but it is not completely working ([details](https://github.com/helloSystem/Menu/issues/61))
* The Python based components are not translatable yet because we have not figured out a way to include the translations without compilation ([details](https://github.com/helloSystem/Utilities/issues/46))
* Components we are just using (rather than making) should be translatable

The language should get detected and set automatically based on your keyboard layout or `prev-lang:kbd` EFI setting.

Closing this ticket in favor of the linked ones.
