### ISSUE TITLE
Consider using only two buttons on window titlebar.

### ISSUE THREAD

**Issue by wesbluemarine** [helloSystem/hello#202]
![two_buttons](https://user-images.githubusercontent.com/14043560/133316705-2408db0e-e172-4733-a5f7-23878447a056.png)

I think could be nice to have only two buttons, like Window Maker, for achieve symmetry.

Maximize/unMaximize can be done with an intuitive double click on titlebar, like many desktop environments.
Shade/unShade can be done with mouse scroll on titlebar, like other desktop environments.
Close button could be more intuitive on the right, like Window Maker, but also like many websites.

**Window Maker default layout**
![wmaker](https://user-images.githubusercontent.com/14043560/133318577-c9a00012-86f8-4ad4-8170-166a9f3382af.png)

**Website Example**
![messaggero](https://user-images.githubusercontent.com/14043560/133318586-811f9ff3-a406-4547-9ec5-d352c3646be8.png)

We can achieve this adding just few line inside ~/.config/kwinrc

```
[Compositing]
GLCore=true
OpenGLIsUnsafe=false

[Desktops]
Id_1=2d010893-505d-4617-8346-b83003495cf5
Rows=1

[MouseBindings]
CommandTitlebarWheel=Shade/Unshade

[Windows]
Placement=Cascade
TitlebarDoubleClickCommand=Maximize

[org.kde.kdecoration2]
ButtonsOnLeft=I
ButtonsOnRight=X

**Comment by probonopd** [comment]
* In accordance with our [reference](https://dl.acm.org/doi/book/10.5555/573097), Close _must_ be on the left-hand side. It has been this way on the Mac since 1984

Also,
* There must be a way to minimize
* There must be a way to maximize

This is where both Classic MacOS and Mac OS X have screwed up imho: Classic MacOS did not provide a way to maximize and to minimize (only somthing vaguely similar on the right-hand side), and Mac OS X put everything to the left, breaking the early-Mac Human Interface Guidelines and putting dangerous (close) options next to non-dangerous ones.

So I think our solution is best:

![image](https://user-images.githubusercontent.com/2480569/133324082-e5f73e09-ee40-4ff1-a39a-c8d8baae6985.png)
