### ISSUE TITLE
Window, menus and dialoge window corners.

### ISSUE THREAD

**Issue by alphamodh0** [helloSystem/hello#280]
In openbox we had rounded corners and they looked great. In addition to giving an image of cleanliness and good design. Can we round the corners in kwin_x11 as well? Don't you think it is an essential part of the design?

Another importat point in the OS design: dock icons.

**Comment by probonopd** [comment]
In helloSystem we have rounded corners on top and non-rounded corners at the bottom, just like in Mac OS X 10.0-10.4. Steve Jobs is said to have personally approved it so that the window resize grip icon can fit into the bottom-right corner.

![image](https://user-images.githubusercontent.com/2480569/145686760-42f92c81-4f15-45d2-a8f4-0676699487e3.png)

Source: [Wikipedia](https://en.wikipedia.org/wiki/Mac_OS_X_10.0#/media/File:MacOSX10-0screenshot.png)

**Comment by alphamodh0** [comment]
At least in what I can appreciate in the image there is a slight rounded in the lower corners (maybe a pixel or two), if you want "softened" but it looks less aggressive than in the current corners. Maybe you think it's silly lon that I propose, but at least I notice a difference. Thanks for answering.

**Comment by probonopd** [comment]
Hi @alphamodh0 right now I am prioritizing on more pressing functional requirements. The whole visual look will need to be reworked eventually. But I am not unhappy with the sharp edges that have served the good versions of Mac OS so well.

**Comment by alphamodh0** [comment]
Strongly agree with implementing functionality over design. Thank you for taking importance to me even though I usually criticize (constructively) what I love and value. Thank you for your effort! Keep going!
