### ISSUE TITLE
Terminal Man pages?

### ISSUE THREAD

**Issue by 69graves** [helloSystem/hello#300]
When I issue 'man' in the terminal, the default is to open a tab in Falkon.

Is this expected behavior, and if so, is there a way for me to change it to appear in the terminal instead?

**Comment by probonopd** [comment]
Yes, in helloSystem we are opening man pages in the web browser.

If you are interested in reading man pages in the Terminal, you need to install the __Developer Tools_ (from were you downloaded the ISO) which contain the man pages, and need to delete (or rename) `/usr/local/bin/man` so that `/usr/bin/man` is used.

**Comment by 69graves** [comment]
Thank you.
