### ISSUE TITLE
FreeBSD man pages missing from default install

### ISSUE THREAD

**Issue by SanPollo** [helloSystem/hello#320]
Please include the FreeBSD man pages as part of the default install.

I regularly work on the command line, and utilise the man command very often. Without it, the only alternative is to look the command up in a browser which slows me down.

**Comment by probonopd** [comment]
Developer-centric command line tools (and man pages) are not shipped on the Live ISO by default in order to reduce its size. This is a feature, not a bug.

As a convenience, typing `man sh` on the command line will open the man page for `sh` in the web browser. This is to save space and because I don't know how to display man pages properly in a non-Terminal fashion on the local machine.

**Comment by SanPollo** [comment]
@probonopd that's fair comment. Those who want to delve deeper can install the Developer Tools. Thanks for the clarification.
