### ISSUE TITLE
Copyright infringement?

### ISSUE THREAD

**Issue by shilch** [helloSystem/hello#38]
Very cool project, I like the idea!  
I found out about it in [this Reddit thread](https://www.reddit.com/r/freebsd/comments/jv02tr/hello_lets_make_a_freebsd_for_mere_mortals/).

One thing that bothers me though is:  
With hello mimicking the Apple Aqua desktop, couldn't there be an issue with Apple having copyright on the look and feel of the system? I'm not talking about copying actual icons - which definitely would be copyright infringement - but the style.  
To give some examples:  
- The three window actions in the top left corner
- The way the dock looks like and works
- The global menu

Can those parts be copied without any issues? What about gestures (e.g. trackpad as can be configured in macOS preferences -> trackpad)?

Thanks!

**Comment by probonopd** [comment]
While this project should be _welcoming to Mac users_, it is not a goal of this project to clone any existing user interface. You will find plenty of differences. In fact, _nothing_ is the same. We are just following some basic underlying ideas, which as mere ideas/design objectives are not protectable. Please let me know if you have indications that suggest otherwise.

* The colors and shape of the three window actions in the top left corner are just abstracted symbols of traffic lights, I doubt they are protectable
* If the idea of a Dock was protectable, then probably [Latte Dock](https://store.kde.org/p/1169519/) and [Dash to Dock](https://extensions.gnome.org/extension/307/dash-to-dock/) would know by now and no longer be available
* If global menus were protected, then probably GNUstep and KDE would know by now and no longer ship them

> Can those parts be copied without any issues?

No, they cannot be _copied_. But I highly doubt that anything can prevent anyone from implementing the basic ideas in similar, albeit not identical ways.

> What about gestures (e.g. trackpad as can be configured in macOS preferences -> trackpad)?

I don't know but as far as I know, touchpad manufacturers like Synaptics and Elan deliver certain basic gestures as part of their drivers.

**Comment by shilch** [comment]
> While this project should be welcoming to Mac users, it is not a goal of this project to clone any existing user interface.

I got that. It's just that Apple has a [long history](https://en.wikipedia.org/wiki/Smartphone_patent_wars) of patent wars and if you look into some of [their smartphone patents](https://news.yahoo.com/apple-wins-mother-smartphone-software-patents-could-spell-201538837.html), it's what we would call trivial stuff.

The reason I'm mentioning trackpad is because Apple actually tried patenting multi-touch in the past. I'm not sure what patents they else have. 😆

**Comment by probonopd** [comment]
Thanks. Closing for now. Feel free to comment/reopen if you have reason to believe that something should be changed very specifically.

**Comment by grahamperrin** [comment]
https://groups.google.com/g/smug/c/5Wp-TuZEmp8/m/GEOWtJzqBQAJ

> There was recently a company who made a full linux clone of macOS and were sued by apple for copyright infringement, something about the visual aesthetic being too close

Requests for clarification were inexplicably deleted: 

![messages disappearing without explanation from SMUG](https://user-images.githubusercontent.com/192271/103934578-1bf6e980-511d-11eb-9a6c-175adec811a3.png)

In the absence of a link, my best guess is **iRaspbian** by Raspbian-X but the infringement here was more likely inclusion of a virtual machine: 

![image](https://user-images.githubusercontent.com/192271/103935185-1bab1e00-511e-11eb-8f35-e4bc20761ef6.png)

From [The Free Operating System That’s Identical To macOS](https://www.forbes.com/sites/barrycollins/2020/05/19/the-free-operating-system-thats-identical-to-macos/) (2020-05-19): 

> As if iRaspbian wasn’t yanking the chain of Apple’s lawyers already, the distro also includes an emulator for Mac OS 9, as well as one for Windows 98.

[What happened to Raspbian-X? - Raspberry Pi Forums](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=274644) (2020-05-20)

----

Rewind to opening post <https://groups.google.com/g/smug/c/5Wp-TuZEmp8/m/blU5KEI2BQAJ>: 

>> … **Definitely not a clone of anything** …
