### ISSUE TITLE
Enter password to perform administrative tasks interface.

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#422]
Although there is already this thing, but it is not easy to notice, and there is no sign in the window that any program needs permission. If it suddenly appears in your unexpected work, it will be dangerous. I hope it is like ubuntu 10.04  The same attention to visuality as the screen.
![image](https://user-images.githubusercontent.com/44593430/206662000-4f5c0482-8fd6-41df-a4a3-0fc5b11d6a8c.png)

**Comment by probonopd** [comment]
You mean, make all other windows dimmed in the background?

**Comment by louies0623** [comment]
Yap

**Comment by louies0623** [comment]
Another thing is to display the account of the administrator, so as to know which account password to enter.
![image](https://user-images.githubusercontent.com/44593430/206841261-2aa2a296-5242-40e6-87ae-0bc6f2f9ab5c.png)

**Comment by probonopd** [comment]
The Windows examples show too much text. Which no one really reads nor understands. helloSystem is meant to be simple.

Changing it to this:

![image](https://user-images.githubusercontent.com/2480569/206852117-67cc6c5f-fc6c-4c8d-b67a-130488263b13.png)

We are now also using the optional `SUDO_ASKPASS_TEXT`) variable. Applications can use this variable to show a more user-friendly explanation text.

**Comment by probonopd** [comment]
We still need to find a way to dim the rest of the screen, or add another visual clue about the importance of this window.

**Comment by louies0623** [comment]
like a welcome video overlay.

**Comment by probonopd** [comment]
Exactly. How to do it in PyQt5?

**Comment by louies0623** [comment]
I hope this network problem can help .youhttps://stackoverflow.com/questions/33982167/pyqt5-create-semi-transparent-window-with-non-transparent-children

**Comment by probonopd** [comment]
Thanks for the hint. Have you tried it out? No one was born as a developer. We all started by trying out things... trial end error until something works.

**Comment by louies0623** [comment]
I've touched it before but held back because I'm poor at comprehension.

**Comment by louies0623** [comment]
![image](https://user-images.githubusercontent.com/44593430/207066806-86e0a324-4534-44ed-9dbe-e1fbb358cefa.png)
You can refer to this LXQT-sudo

**Comment by probonopd** [comment]
Looks like it also doesn't have this functionality.

![image](https://user-images.githubusercontent.com/2480569/207127123-8deb7cb3-aa2a-4c4e-a14a-0d472822a55d.png)

**Comment by louies0623** [comment]
Then the next best thing is to generate a transparent black window in the background.

**Comment by louies0623** [comment]
[image](https://user-images.githubusercontent.com/44593430/215670000-1530cee2-cbf8-4faa-8032-592c987a811b.png)
Maybe it's possible to just show the background, e.g. like Windows 8 UAC

**Comment by probonopd** [comment]
If anyone wants to work on this, I will consider pull requests, but it is not important enough for me to work on it.

**Comment by louies0623** [comment]
@Hierosme You have a good job, can you help @probonopd this question?
![image](https://github.com/helloSystem/hello/assets/44593430/81592651-66e1-492f-a420-e5c6c136dfa7)

**Comment by Hierosme** [comment]
Not sure, but let me explain some basics arround it.


Only the QDesktop  class can speack about a entry screnn + virtual desktop.
Normaly NO windows is allowed to touch the entire screen.

The split is clear, The QDesktop class work with the entire screen, where a QWindow can't.
In general that done by use  Dbus + Session Manager + Desktop Agent ready for it type of event (a bit Like Notification finaly)

A Small link aboutGNOME nd KDE work https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html
Polkit is a huge Gaz engine and nobody never know if it work for tue ...

helloSystem use Sudo, that is totaly a oposit method, and from my point it have no chance to get the same type of result. 

It have globaly two method

1) change owner execution of child  programme (Sudo)

or

2) Ask to somthing it allow or not  the exchange. (Polkit)


if helloSystem want the same type of result freedesktop provide framework. 
Unfortunally Polkit is a FreeDektop core component, it have nothing relatif with a Application Window.

Deporte the responssability to the application, mean use Sudo, but the design of Sudo not permit to a allready started application to change it owner, it must create a child process via sudo command.

Nobody have say it was simple ....

Regards

**Comment by Hierosme** [comment]
My recommendation is to follow FreeDesktop recommendation, and in that case, take a look on the terrific Polkit ....

That a big pain....

**Comment by probonopd** [comment]
We don't want Polkit in helloSystem. `sudo` is much simpler.

https://github.com/helloSystem/hello/wiki/Welcome-and-unwelcome-technologies

**Comment by Hierosme** [comment]
Hooo that insteresting.

If the choise is all ready done. >>> **SUDO** <<< , then the fixe is to askpass before the start of the application...

I really want to be clear Sudo / Polkit is TOTALY not similar... Nothing is similar really, the method is diffrent and the result is different etc ....

It exist a project call Ansible it have really push the use of sudo. I fact want we can optain with sudo is near whar the Ansible roject have optian.

Sudo have 2 huge limitation:

- Only Sudo child process great permission
- Impossible to Jump to a Child process and back again to the Parent....  (Due to the first rule)

What is possible to do is restart the Application in place syscall HUP great permission, and restart again. Normaly THAT is possible.

for better understanding, a QT Application use signal anf by change the PID (Process ID, PRocess is a application execute under a environement) signals will be lost. Normaly the way is to use a BUS.

What is important is **A Process is a application execute under a environement** , that mean wew can restart in place and IMPOSE the contain a environement variables. <-------- Here is the key.

Normlay a True Security Policy should stop us here ..... But it look to not under helloSystem that mean out of the box we can use the sudo option -E --preserverve-env. It certainly add chainning security issue, but it look possible.

Soon i'll be in front of the trouble with a hammer...
Regards

**Comment by probonopd** [comment]
We want things to be _simple_.

**Comment by Hierosme** [comment]
I'll do my best for that ....
