### ISSUE TITLE
Weird audio

### ISSUE THREAD

**Issue by louies0623** [helloSystem/hello#446]
The sound of the system sounds like it is speeding up, which is unpleasant and weird.
Build 0H246
[music Scarlet Fire](https://archive.org/download/scarlet-20-fire-20-20-otis-20-mc-donald-2/Scarlet%2520Fire%2520-%2520Otis%2520McDonald%202.mp3)

**minitube**

[PC-2-screen0.webm](https://user-images.githubusercontent.com/44593430/208226506-51151340-898d-423c-b86e-1fd353c9e7a1.webm)

**MP3 Player**

[PC-2-screen0.webm](https://user-images.githubusercontent.com/44593430/208226879-1db91035-9afa-4651-8619-2c1932b8f2cb.webm)

**Falkon**

[PC-2-screen0.webm](https://user-images.githubusercontent.com/44593430/208226723-6b926bdf-43f9-4ef1-bf3a-7b6210350b36.webm)

**Comment by probonopd** [comment]
Looks like you have discovered Adele's intro song for helloSystem ;-)

It sounds too fast in your recording indeed, but it sounds correct on my local development system.

Are you running this in any sort of virtualization?

**Comment by louies0623** [comment]
Yes, I use a virtual computer, as you said, the physical machine is normal, weird...

**Comment by probonopd** [comment]
This is why I am saying "I can't debug VMs" ;-)

**Comment by louies0623** [comment]
Recently seen, this may be the reason, the VM sound driver does not have the right sampling.

https://www.reddit.com/r/DankPods/comments/zg57id/this_is_what_happens_when_you_force_thx_speakers/

**Comment by probonopd** [comment]
Can you verify that the issue goes away with another setting? If so, which setting should we be using?

In general, when reporting issues it would abe great if you could give a concrete (tested) suggestion of what/how to change. This would be very helpful, since I usually don't have enough time to find out what may or may not work by following some instructions on the internet by trial and error.
