### ISSUE TITLE
Lock Screen

### ISSUE THREAD

**Issue by midnadimple** [helloSystem/hello#478]
A lockscrren / login screen should be implemented for privacy and security. I think it should be added as a PyQT utility that can be chosen to be on or off.

**Comment by probonopd** [comment]
For me personally, this is not a high priority at the moment since 
* It did not exist on the Mac until System 8 or so
* These things provide a false sense of "security" unless the storage media is encrypted

But if someone would like to help contribute code to https://github.com/helloSystem/LoginWindow, it would be highly welcome. The UX is there but the
