### ISSUE TITLE
Untangle the different desktop components

### ISSUE THREAD

**Issue by probonopd** [helloSystem/hello#5]
These distinctions are normally not clear to Mac users, where "the desktop" "just exists" (and WindowServer and "Quartz" somehow do the magic)...

* Display manager: What shows the login screen. Xfce uses `lightdm`. Since we don't want to show a login screen on a single-user personal system we may just as well want to use `nodm` as the display manager. This is set in `/etc/X11/default-display-manager`.
* Window manager: What applies theming to windows. Xfce uses `xfwm4`. Is it also resposible for drawing the drop shadow behind windows? Compiz is an OpenGL compositing window manager, which might be handy for smooth animation effects?

**Comment by probonopd** [comment]
https://gist.github.com/probonopd/88551761e4da515817ba924681f0d5e5

**Comment by binarica** [comment]
`nodm` would be an interesting choice, as it is small and non-intrusive. Just as a heads-up, there's a [fix](https://github.com/spanezz/nodm/commit/64fa67b36da4cc0cb8460b5da66b6e564e0be752) to a [shutdown bug](https://github.com/spanezz/nodm/issues/5) that hasn't been merged to upstream due to the project being [abandoned](https://github.com/spanezz/nodm#this-repository-is-not-maintained), although it probably doesn't affect FreeBSD's init system.

Another option could be something like [xlogin](https://github.com/joukewitteveen/xlogin) but rewritten as an `rc.d` script.

**Comment by probonopd** [comment]
Thanks @binarica. For now we are using slim as the Display manager and Openbox as the Window manager. Both might change in the future if the need arises.
