### ISSUE TITLE
The window manager, the Filer, the Dock and the Launcher should be in the same executable

### ISSUE THREAD

**Issue by kallaip** [helloSystem/hello#82]
Hi Guys,

I've run into your excellent project on the Hungarian Unix Portal three days ago, and I became addicted to this. :-) I was thinking of a similar system a for long time (>10 years) now, but I've never started it, mostly because lack of people sharing the same idea. So, I'm pretty impressed of it, I'm researching your project for 3 days for now, and I share my most important thought first.

As you might've seen in the title, it is about system integrity. I think, that the window manager, **the Filer, the Dock, the Launcher and maybe the central Menu also should be integrated within one single executable**. 

Reasons I think this would be good:
- This is the most important part of the system, which the user is constantly related with. So, it should be highly optimized, and integrated.
- This would increase portability (and ability to simply copy it) because of the less software unit to integrate.
- This would radically simplify configuration and make it unified (I think of the configuration from the aspect of the developer not the user. F.g. think of the window manager, whose config is totally different and separated)
- Using only one executable eliminates the need of IPC in many cases, data exchange is more direct, which makes the development more more easier, and the application more efficient.
- There would be no chance to became the system partly unavailable, it works or not works. (Here I think of a case I have experienced yesterday, when the filer crashed, and the menu of the window manager appeared on right click, this confuses the user.)
- This executable can act as a graphical system shell also, so launching and managing the other integrated applications made be easier.
- System animations, window tweaks, etc. would be easier to achieve, it would not depend on whims of the underlaying window manager.
- System load time would be less because of the less component and file to load.
- There would be no such thing that we "can't do" because of limitations coming from the separately executing parts. It would "Just work". :-)
- Some bugs will be eliminated upon the integration itself, and bug tracking becomes easier

I know, this is not too simple, but it can be done by finding a window manager with appropriate license which permits reusage of code parts of it, customizing for the needs of this project and integrating the core applications into it. 
Other applications remain separate of course, and PyQt is great for them, but this core application should be optimized and made in C++ (as the distinct components are already being). I think I have the knowledge and willingness to do this, so, if you think this is a good direction, I would be glad to contribute and help to Make the Desktop Great Again :D.

My vision is that at the end we will have a great desktop OS, which is productive, lightweight and human-bearable.

A few words about myself (I put this here since I didn't find a more generic thread and this is my first issue):

I'm from the not-too-young generation of computer enthusiasts (I'm 45), I was starting my computer experience with Commodore computers, around 1986. Later I've met with the IBM PC computer family, and everything were beautiful :). Computers were simple and functional. I've met with Linux in 1994, I have used Slackware first (the release was 1.2 or sg. like that as I remember), and for a long time. I was a maniac on gathering of a good and efficient desktop environment, since I always had outdated hardware. Later I have compiled X server for myself with the latest direct rendering engine to support HW 3D, and with similar tasks I killed my time. 
After getting my first degree as Electrical Engineer, I worked as an entrepreneur, and I have made a lot of commercial projects with the use of free software, and with Linux (this was 10 to 20 years before from now). I became a real Linux (and Unix) evangelist, I wanted to solve everything with free software. 

In the meantime, the GNU software family turned on a way I didn't like more and more: core libraries (including GLIBC) became overcomplicated, everything has been made to be generic, but nothing has been really "done", things not working out of the box. Linux distros turned to have a burning hell of library dependency issues when you want to install something, and desktops became more slower and bloated, nearly impossible to use. My enthusiasm for these systems became a little worn out, because of the difficulties, which don't seem to disappear over the time. The description of GNU: "GNU is Not Unix" became sadly true for today.  For the recent days, f.g. Ubuntu desktop is far slower on the same machine as Windows 10, which is a shame. 

I also totally agree with all the principles layed around this project, especially with the 6 part Linux UX series, which describes the problem of today's free sofware (not only Linux desktop) very well. 

Now, I'm working at a local company, we are making FDA regulated software for US companies, which are present in the blood industry worldwide. At the moment I'm working under windows environment (for earning money), but I didn't give up with Unix-like systems, I really like BSD, and very glad to find this project. I think at the moment I have my best experience in C/C++, but I did things in a bunch of languages, also Python.
Sorry if I'm telling too much about myself, this is only frame to describe what happened in the free sofware industry over the years :).

Have a nice time guys,
 I'm courios if you agree with my thoughts (I have yet many more), I will contribute as much as I can. :-)

**Comment by probonopd** [comment]
Hello @kallaip. Nice to hear from you!

> I think, that the window manager, the Filer, the Dock, the Launcher and maybe the central Menu also should be integrated within one single executable.

Interesting point. I have had the same thought for a while, but then decided that Menu, Dock, and Filer should be separate applications.

Reasons for keeping Menu, Dock, and Filer separate:
* __Pragmatism__: Dock and Filer were not written from scratch but are forks of existing projects
* __Modularity__: We may want to switch out e.g., the current Filer implementation with a completely different code base
* __Unix philosophy__: Do one thing only, but to it well
* __System robustness__: Especially during development it is not uncommon (in fact, it is quite frequent) that we need to kill or restart one of those components. It would be annoying if the whole desktop would disappear. This is especially true for the case of unexpected crashes
* __People's expectations__: Most people will expect the system to work in the way that we currently have (I know, that is never a _sufficient_ reason to do anything)

> So, it should be highly optimized, and integrated.

The only optimization I could see is the removal of the need for IPC between those components through D-Bus. But then, since existing applications depend on D-Bus anyway, we would not win much by such a move.

In terms of integration, KDE is highly integrated and frankly it results in a "all or nothing" system which doesn't seem to be all that popular with many BSD users. For example, I'd like to use the Falkon browser but I don't want to incur all those dependencies geared toward a KDE Plasma desktop. So helloSystem will try to make sure that we don't have a lot of cross-dependencies.

For example, when writing applications, I avoid to have them depend on anything that is not in ports. This leads to some code duplication but I think the decoupling and robustness is worth it.

> This would increase portability (and ability to simply copy it) because of the less software unit to integrate.

Portability to where? The components of the helloDesktop system are currently tested nowhere else but on helloSystem. And it is unlikely that we support running helloDesktop compoents on other systems than helloSystem. Basically because every Linux distribution introduces breakage in slightly different ways, and they are "moving targets". I simply don't have the capacity to keep up with this. This was one reason for choosing FreeBSD as the base.


> There would be no chance to became the system partly unavailable, it works or not works. (Here I think of a case I have experienced yesterday, when the filer crashed, and the menu of the window manager appeared on right click, this confuses the user.)

Yes, and this I think is dangerous. I have seen the Filer crash, which also results in the icons on the desktop and the wallpaper to disappear, but luckily Menu and Dock are still there, allowing one to restart the Filer somehow...

> This executable can act as a graphical system shell also, so launching and managing the other integrated applications made be easier.

For this, please check out our launch tool. It will be expanded in the future to get _Launch Services_ like capabilities.

> System animations, window tweaks, etc. would be easier to achieve, it would not depend on whims of the underlaying window manager.

Well, this is an excellent point. 

Animations are one area in which helloSystem currently is still very much lacking. For example, when I open a folder in Filer, then the folder icon should be visibly morphed into the opened folder window. (This is all happening _inside_ Filer, so we should start there with the animations.)

However, I think that having Menu, Dock, and Filer in one application would achieve little unless we would also integrate the functionality of a window manager. And this is clearly above my current capabilities. Especially since existing applications would still need to work, so we would need to provide window manager functionality to them as well.

> System load time would be less because of the less component and file to load.

I think the system load time is currently mainly determined by the FreeBSD rc script order. It takes almost no time from the point where Xorg gets started to a fully functional desktop.

If we care about system load time, we need to find a way to do _everything network related_ __after__ launching slim/Xorg. This would have a _huge_ impact.

> I know, this is not too simple, but it can be done by finding a window manager with appropriate license which permits reusage of code parts of it, customizing for the needs of this project and integrating the core applications into it.

Yes, this would be one way to go about it. It should be a Qt based window manager. How many are out there? I am only aware of kwin. And if we did this, then we would sit on a fork of kwin that we would have to maintain. This is not something I would want to do as a hobby.

> Other applications remain separate of course, and PyQt is great for them, but this core application should be optimized and made in C++ (as the distinct components are already being).

Yes. I think PyQt is a great environment for simple components such as Utilities and Preferences applications. But the long-running core elements of the desktop are written in C++/Qt.

> I think I have the knowledge and willingness to do this, so, if you think this is a good direction, I would be glad to contribute and help to Make the Desktop Great Again :D.

Cool! Do you have Qt experience? If so, it would be _super awesome_ if we could win you as a contributor for the helloSystem project.

To begin with, I think we have a lot of _much_ lower-hanging fruit than what you are proposing, including:

* Finding another base for Filer that ideally 
  * Has no dependencies on gvfs (but still allows to browse the network)
  * Has Miller columns (like [DFilemanager](https://github.com/probonopd/dfilemanager) - can you get it to compile on FreeBSD?)

* Improving the deficiencies in Menu for which I have not found solutions yet (been learning Qt along learning FreeBSD while making helloSystem)

> My vision is that at the end we will have a great desktop OS, which is productive, lightweight and human-bearable.

If you are interested in contributing, https://hellosystem.github.io/docs/developer/contributing is a great place to start.

If you have Qt experience, then please consider looking at [issues we need help with](https://github.com/search?q=org%3AhelloSystem+is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) to see whether there is something you know how to implement.

And it would be great to see you in the `#helloSystem` channel on `irc.freenode.net` or on Matrix.

Welcome to hello!

**Comment by probonopd** [comment]
> In the meantime, the GNU software family turned on a way I didn't like more and more: core libraries (including GLIBC) became overcomplicated, everything has been made to be generic, but nothing has been really "done", things not working out of the box.

Very well said!

Have you seen my [posts on Medium](https://medium.com/@probonopd)?

**Comment by kallaip** [comment]
Hi @probonopd, thanks for considering my idea, and I agree with your points, these are good reasons to have the components separate. By the way, from the aspects of the animations only, later we may have a modified window manager, which belongs to helloSystem and which can be notified f.g. if where to start an animation or so on.

Yes, I have some Qt experience, but from the Qt3 times, I think I can get recent with it in not much time. Thank you  for the invitation, I will find an issue which I can deal with, and I will do improvements. Since I decided today that I would like to contribute, at the moment I'm setting up a FreeBSD dev environment to be able to do something :-) .

Do you have some annotations about dev environment? 

Thanks again, I will ring the bell soon : )


Peter

**Comment by kallaip** [comment]
Ps: I think we can close this issue, just to make things up to date. :)

**Comment by probonopd** [comment]
>  I'm setting up a FreeBSD dev environment to be able to do something :-) .

Cool! I'd recommend that you install https://github.com/helloSystem/ISO/releases/tag/12.1-experimental to its own SSD. That's what I have done, anyway ;-)
